export const nameBand = 'POWER RANGERS - WILD FORCE';
export let nameSongs = [
	"WILD FORCE THEME", /*1*/
	"CALLING ALL ZORDS", /*2*/
		"THE SONG OF ANIMARIA", /*3*/
	"THE THEME OF ZEN AKU", /*4*/
	"PREDAZORD AWAKEN", /*5*/
	"LUNA WOLF RANGER THEME SONG BGM", /*6*/
	"GO GO POWER RANGERS", /*7*/
	"ZEN AKU - FLUTE MUSIC", /*8*/
	"ZEN-AKU FLUTE THEME 12 MINUTES ", /*9*/
	"SEARCH FOR THE CRYSTALS", /*10*/
	"NEVER GIVE UP", /*11*/
	"THE RED SAVAGE WARRIOR", /*12*/
	"THE TITANIUM RANGER", /*13*/
	"WILD ACCESS", /*14*/
	"JUNGLE PRAISE", /*15*/
	"EAGLE RISING", /*16*/
	"CALL OF THE PRINCESS", /*17*/
	"FEAR CANYON", /*18*/
	"ANIMAL SPIRIT", /*19*/
	"MAY THE POWER PROTECT YOU, ALWAYS", /*20*/
]